# Generated by Django 4.2.4 on 2023-09-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_alter_contact_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
