# Generated by Django 4.2.4 on 2023-09-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_alter_contact_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
